import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeadDoc from "./_components/HeadDoc";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import FooterDoc from "./_components/FooterDoc";
import Aside from "./_components/Aside";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <HeadDoc />

      <body className={inter.className}>
        <Header />
        <Aside />
        {children}
        <Footer />
        <FooterDoc />
      </body>
    </html>
  );
}
